<!--HEADER START-->
<header id="header">
  <div class="welcome">
    <a class="logo device-hide" href="#" title="Ermenegildo Zegna">
      <img src="<?php echo $this->basePath('images/logo.png') ?>" alt="Ermenegildo Zegna"/>
    </a>
    <a class="logo btn-menu device-show" href="#" title="Ermenegildo Zegna">
      <span class="logo"><?php echo $this->translate('Ermenegildo Zegna') ?></span>
      <span class="device-show icon-menu"></span>
    </a>
    <span class="device-hide"><?php echo $this->translate('Welcome to Zegna.com Store Locator') ?></span>
  </div>
  <ul class="device-show action-bar-mobile">
    <li><a class="map active" href="#" title="" data-icon="D"></a></li>
    <li><a class="map-link" href="/" title="" data-icon="D"></a></li>
    <li><a class="store" href="#" title="" data-icon="S"></a></li>
  </ul>
  <nav class="navigation-bar">
    <ul>
      <li><a class="contact" href="#" title=""><?php echo $this->translate('Contact us') ?></a></li>
      <li><a class="store-list" href="#" title=""><?php echo $this->translate('Store list') ?></a></li>
      <li class="wrap-store-concept"><a class="store-concept" href="#" title=""><?php echo $this->translate('Store Concept') ?></a></li>
      <li class="wrap-store-concept-link"><a class="store-concept-link" href="/store-concept" title=""><?php echo $this->translate('Store Concept') ?></a></li>
    </ul>
  </nav>
</header>
<!--HEADER END-->