<?php echo $this->doctype(); ?>

<html lang="<?php echo $this->lang?>">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Ermenegildo Zegna') . ' ' . $this->translate('Store Locator'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath() . '/styles/screen.min.css')
            //web fonts
            ->appendStylesheet('http://fast.fonts.net/cssapi/13b88c29-eae9-4f7b-be22-b73db30a85f8.css')
    ;
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()
            //modernizr
            ->appendFile($this->basePath() . '/scripts/lib/modernizr-2.6.1.js', 'text/javascript', array('charset' => 'utf-8',))
            //google maps
            ->appendFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyBaZuFT0-IAXWyC9_k4psUPPl8qEnod6fU&sensor=true')
    ;
    ?>

  </head>
  <body data-publicpath=""<?php if($this->body_class):?> class ="<?php echo $this->body_class;?>"<?php endif;?>>
  <?php
  echo $this->content;
  ?>
    
      <?php
  //here we include all the scripts. We should minify them!!!
  echo $this->InlineScript()
          //lib
          ->appendFile($this->basePath() . '/scripts/lib/jquery.min.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/jquery.touchSwipe.min.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/iscroll.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/scroller/Raf.js')
          ->appendFile($this->basePath() . '/scripts/lib/scroller/Animate.js')
          ->appendFile($this->basePath() . '/scripts/lib/scroller/EasyScroller.js')
          ->appendFile($this->basePath() . '/scripts/lib/scroller/Scroller.js')
          ->appendFile($this->basePath() . '/scripts/lib/jquery.history.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/EventEmitter.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/greensock/TweenLite.min.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/greensock/easing/EasePack.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/greensock/plugins/CSSPlugin.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/infobox.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/lib/geolocationmarker.js', 'text/javascript', array('charset' => 'utf-8',))
          //app
          ->appendFile($this->basePath() . '/scripts/social_sharing.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/filter_manager.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/map_manager.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/map_controller.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/store_info.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/resize_element.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/slider_mousefollower.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/slider.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/input_placeholder.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/tab_controller.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/header_controller.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/mobile_controller.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/store_list.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/get_direction.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/splash.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/scrollbar_helper.js', 'text/javascript', array('charset' => 'utf-8',))
          ->appendFile($this->basePath() . '/scripts/application.js', 'text/javascript', array('charset' => 'utf-8',))
  ;
  ?>
    
</body>
</html>
