<?php echo $this->doctype(); ?>

<html lang="<?php echo $this->lang?>">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Ermenegildo Zegna') . ' ' . $this->translate('Store Locator'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath() . '/styles/screen.min.css')
            //web fonts
            ->appendStylesheet('http://fast.fonts.net/cssapi/13b88c29-eae9-4f7b-be22-b73db30a85f8.css')
    ;
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()
            //modernizr
            ->appendFile($this->basePath() . '/scripts/lib/modernizr-2.6.1.js', 'text/javascript', array('charset' => 'utf-8',))
            //google maps
            ->appendFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyBaZuFT0-IAXWyC9_k4psUPPl8qEnod6fU&sensor=true')
    ;
    ?>

  </head>
  <body>
  <?php
  echo $this->content;
  ?>
</body>
</html>
